#!/bin/bash

sfdisk /dev/sda <<EOF
d
d
d
d
n
p
1
d
+200M
n
p
2
d
+12G
n
p
3
d
+25G
n
p
4
d
d
w
EOF


mkfs.ext4 /dev/sda1
mkswap /dev/sda2
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda4
swapon /dev/sda2 
mount /dev/sda3 /mnt
mkdir /mnt/home
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mount /dev/sda4 /mnt/home

pacstrap /mnt base base-devel dialog vim networkmanager

genfstab 
genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt 

systemctl enable NetworkManager

pacman -S grub

grub-install --target=i386-pc /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

passwd <<EEOF
toor
EEOF

exec vim /etc/locale.gen
exec locale-gen

echo LANG=en-US.UTF-8 >> /etc/locale.conf
export LANG=en_US.UTF-8

exec ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime

echo archpad >> /etc/hostname


