#!/bin/bash


timedatectl set-ntp true

echo Beginning partioning 

sfdisk /dev/sda <<EOF
d
4
d
3
d
2
d
1
n
p
1
d
+200M
n
p
2
d
+12G
n
p
3
d
+25G
n
p
4
d
d
w
EOF

echo Creating filesystems
mkfs.ext4 /dev/sda1
mkswap /dev/sda2
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda4
swapon /dev/sda2 
mount /dev/sda3 /mnt
mkdir /mnt/home
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mount /dev/sda4 /mnt/home

pacstrap /mnt base base-devel linux linux-firmware git networkmanager vim netctl

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt
 
