#!/bin/bash
wifi-menu
ping archlinux.org -c 5
timedatectl set-ntp true
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk ${TGTDEV}
    d # del
      # part
    d # del
      # part
    d # del
      # part
    d # del
      # part
    n # first partition
    p # primary
      # default
      # default
    +200M # 200M Partition
    n # first partition
    p # primary
      # default
      # default
    +12G # 12G Partition
    n # first partition
    p # primary
      # default
      # default
    +15G # 15G Partition
    n # first partition
    p # primary
      # default
      # default
      # Take all disk home
    w # write changes
    q # exit
EOF
lsblk 
read Continue?
#File Systems
mkfs.ext4 /dev/sda1
mkswap /dev/sda2
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda4
swapon /dev/sda2 
mount /dev/sda3 /mnt
mkdir /mnt/home
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mount /dev/sda4 /mnt/home
read Continue?
#Only US Mirrors
pacman -Syy
pacman -S reflector
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
reflector -c "US" -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist
read Continue?
#Base install
pacstrap /mnt base base-devel linux linux-firmware git networkmanager vim netctl

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime
arch-chroot /mnt hwclock --systohc

arch-chroot /mnt pacman -S grub
arch-chroot /mnt grub-install --target=i386-pc 
arch-chroot /mnt grub-mkconfig -o /boot.grub.cfg
read Continue?
echo "Enter Password"
arch-chroot /mnt passwd
